---
# handlers file for hhvm
- name: restart nginx
  become: yes
  service: name=nginx state=restarted

- name: restart hhvm
  become: yes
  service: name=hhvm state=restarted

- name: hhvm repo mode
  shell: /usr/bin/hhvm-repo-mode enable /var/www/html
